# Generated by Django 5.1.1 on 2024-09-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_rename_reference_address_reader_reader_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='reader_contsct',
            new_name='reader_contact',
        ),
    ]
