# Generated by Django 5.1.1 on 2024-09-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_rename_reader_contsct_reader_reader_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=200)),
                ('books_name', models.CharField(max_length=200)),
                ('books_contact', models.CharField(max_length=200)),
                ('books_address', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
